# 审批状态常量
APPROVAL_STATUS_DRAFT = "draft"
APPROVAL_STATUS_PENDING = "pending_approval"
APPROVAL_STATUS_APPROVED = "approved"
APPROVAL_STATUS_REJECTED = "rejected"

# 所有审批状态
APPROVAL_STATUSES = [
    APPROVAL_STATUS_DRAFT,
    APPROVAL_STATUS_PENDING,
    APPROVAL_STATUS_APPROVED,
    APPROVAL_STATUS_REJECTED,
]

# RAGFlow 状态常量
RAGFLOW_STATUS_NOT_INDEXED = "not_indexed"
RAGFLOW_STATUS_QUEUED = "queued"
RAGFLOW_STATUS_INDEXING = "indexing"
RAGFLOW_STATUS_INDEXED = "indexed"
RAGFLOW_STATUS_FAILED = "failed"
RAGFLOW_STATUS_STALE = "stale"

# 所有 RAGFlow 状态
RAGFLOW_STATUSES = [
    RAGFLOW_STATUS_NOT_INDEXED,
    RAGFLOW_STATUS_QUEUED,
    RAGFLOW_STATUS_INDEXING,
    RAGFLOW_STATUS_INDEXED,
    RAGFLOW_STATUS_FAILED,
    RAGFLOW_STATUS_STALE,
]
