# RAGFlow 任务状态常量
RAGFLOW_TASK_STATUS_QUEUED = "queued"
RAGFLOW_TASK_STATUS_INDEXING = "indexing"
RAGFLOW_TASK_STATUS_INDEXED = "indexed"
RAGFLOW_TASK_STATUS_FAILED = "failed"

# 所有 RAGFlow 任务状态
RAGFLOW_TASK_STATUSES = [
    RAGFLOW_TASK_STATUS_QUEUED,
    RAGFLOW_TASK_STATUS_INDEXING,
    RAGFLOW_TASK_STATUS_INDEXED,
    RAGFLOW_TASK_STATUS_FAILED,
]

# 终态
RAGFLOW_TASK_FINAL_STATUSES = [
    RAGFLOW_TASK_STATUS_INDEXED,
    RAGFLOW_TASK_STATUS_FAILED,
]
