# 审批记录状态常量（与 document_doc 中的审批状态一致）
APPROVAL_RECORD_STATUS_PENDING = "pending_approval"
APPROVAL_RECORD_STATUS_APPROVED = "approved"
APPROVAL_RECORD_STATUS_REJECTED = "rejected"

# 所有审批记录状态
APPROVAL_RECORD_STATUSES = [
    APPROVAL_RECORD_STATUS_PENDING,
    APPROVAL_RECORD_STATUS_APPROVED,
    APPROVAL_RECORD_STATUS_REJECTED,
]
