# Runtime session 状态
RUNTIME_SESSION_STATUS_IDLE = "idle"
RUNTIME_SESSION_STATUS_STREAMING = "streaming"
RUNTIME_SESSION_STATUS_WAITING_HUMAN = "waiting_human"
RUNTIME_SESSION_STATUS_COMPLETED = "completed"
RUNTIME_SESSION_STATUS_FAILED = "failed"
RUNTIME_SESSION_STATUS_CANCELLED = "cancelled"

RUNTIME_SESSION_STATUSES = [
    RUNTIME_SESSION_STATUS_IDLE,
    RUNTIME_SESSION_STATUS_STREAMING,
    RUNTIME_SESSION_STATUS_WAITING_HUMAN,
    RUNTIME_SESSION_STATUS_COMPLETED,
    RUNTIME_SESSION_STATUS_FAILED,
    RUNTIME_SESSION_STATUS_CANCELLED,
]

# Runtime 事件类型（与 PRD 对齐）
RUNTIME_EVENT_RUN_START = "run_start"
RUNTIME_EVENT_MESSAGE_DELTA = "message_delta"
RUNTIME_EVENT_MESSAGE_FINAL = "message_final"
RUNTIME_EVENT_TOOL_CALL = "tool_call"
RUNTIME_EVENT_TOOL_RESULT = "tool_result"
RUNTIME_EVENT_VALUE_SNAPSHOT = "value_snapshot"
RUNTIME_EVENT_CUSTOM_EVENT = "custom_event"
RUNTIME_EVENT_SUBGRAPH_EVENT = "subgraph_event"
RUNTIME_EVENT_INTERRUPT = "interrupt"
RUNTIME_EVENT_RESUME = "resume"
RUNTIME_EVENT_RUN_END = "run_end"
RUNTIME_EVENT_ERROR = "error"
RUNTIME_EVENT_RESULT_MATERIALIZED = "result_materialized"
RUNTIME_EVENT_DOCUMENT_PERSISTED = "document_persisted"

RUNTIME_EVENT_TYPES = [
    RUNTIME_EVENT_RUN_START,
    RUNTIME_EVENT_MESSAGE_DELTA,
    RUNTIME_EVENT_MESSAGE_FINAL,
    RUNTIME_EVENT_TOOL_CALL,
    RUNTIME_EVENT_TOOL_RESULT,
    RUNTIME_EVENT_VALUE_SNAPSHOT,
    RUNTIME_EVENT_CUSTOM_EVENT,
    RUNTIME_EVENT_SUBGRAPH_EVENT,
    RUNTIME_EVENT_INTERRUPT,
    RUNTIME_EVENT_RESUME,
    RUNTIME_EVENT_RUN_END,
    RUNTIME_EVENT_ERROR,
    RUNTIME_EVENT_RESULT_MATERIALIZED,
    RUNTIME_EVENT_DOCUMENT_PERSISTED,
]

RUNTIME_PROVIDER_DEERFLOW = "deerflow"

OWNER_TYPE_JOB = "job"
OWNER_TYPE_DOCUMENT = "document"
